Dream.Web.AfterSchool/Controllers/CommonController.cs
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using System.Security.Claims;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Dream.Web.AfterSchool.Core.Entities;
using Dream.Web.AfterSchool.Core.Repository;

namespace Dream.Web.AfterSchool.Controllers
{
    public class CommonController : BaseController
    {
        public ActionResult UserInformation()
        {
            ViewBag.SubTitle = string.Format("정보수정");
            int midx = 0;
            int.TryParse(AppIdentity.Midx, out midx);

            memberRepository mRepository = new memberRepository();
            SchoolInfosRepository sRepository = new SchoolInfosRepository();

            var user = mRepository.memberSelectItem(new member() { midx = midx });
            var schools = sRepository.SchoolInfosSelect(new SchoolInfos());

            return View(new Tuple<List<SchoolInfos>, member>(schools, user));
        }

        [HttpPost]
        public JsonResult SetUserInformation(member item2)
        {
            try
            {
                memberRepository mRepository = new memberRepository();
                mRepository.memberUpdate(item2);

                var updatemember = mRepository.memberSelectItem(item2);

                var identity = (ClaimsIdentity)User.Identity;
                IEnumerable<Claim> claims = identity.Claims;
                var emailClaim = AppIdentity.Email;
                var SchoolNameClaim = claims.Where(c => c.Type == "School").SingleOrDefault();
                var userinfoClaim = claims.Where(c => c.Type == "setuserinfo").SingleOrDefault();

                foreach (string claimName in new string[] { "Email", "School", "setuserinfo" })
                {
                    var tClaim = claims.Where(c => c.Type == claimName).SingleOrDefault();
                    if (tClaim != null)
                    {
                        identity.TryRemoveClaim(tClaim);
                    }
                }

                identity.AddClaim(new Claim("Email", updatemember.email));
                identity.AddClaim(new Claim("School", string.IsNullOrEmpty(updatemember.school) ? "드림고등학교" : updatemember.school));

                if (string.IsNullOrEmpty(updatemember.sch_code) || string.IsNullOrEmpty(updatemember.grade) || updatemember.mclass == null || string.IsNullOrEmpty(updatemember.no) || string.IsNullOrEmpty(updatemember.uname) || string.IsNullOrEmpty(updatemember.sch_code))
                {
                    identity.AddClaim(new Claim("setuserinfo", "Y"));
                }

                HttpContext.GetOwinContext().Authentication.AuthenticationResponseGrant = new AuthenticationResponseGrant(new ClaimsPrincipal(identity), new AuthenticationProperties { IsPersistent = false });

                return Json(new
                {
                    ok = true,
                    message = "수정하였습니다."
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    ok = true,
                    message = "오류가 발생하였습니다."
                });
            }
        }
    }
}

Dream.Web.AfterSchool/Views/Common/UserInformation.cshtml
@model  Tuple<List<Dream.Web.AfterSchool.Core.Entities.SchoolInfos>, Dream.Web.AfterSchool.Core.Entities.member>

@{
    ViewBag.Title = "학교연합교육과정";
    ViewBag.Description = "학교정보수정";
    ViewBag.Navigation = Dream.Web.AfterSchool.Controllers.AppIdentity.UserType == "STUDENT" ? "LECTUREREQUEST" : "LECTUREMANAGE";
    ViewBag.MidNavigation = "LECTURE";
    Layout = "~/Views/_Layout.cshtml";
}

<style type="text/css">
    th {
        font-weight: bold !important;
    }
</style>

<script type="text/javascript">
    var modify = function () {
        event.preventDefault();
        if ($("#username").val().trim() == "") {
            alert("이름을 입력해 주세요.");
            return;
        }

        if (!$("#agreeinfo").prop("checked")) {
            alert("개인정보 수집에 동의하지 않았습니다.");
            return;
        }

        var url = $("#userinfo")[0].action;

        $.ajax({
            url: url,
            data : $("#userinfo").serialize(),
            type: 'POST',
            beforeSend: function () {
                
            },
            complete: function () {
                
            }
        })
            .done(function (data) {
            if (data.ok) {
                alert(data.message);
                //document.location.href = "@Url.Action("Index", "Home")";
            } else {
                alert(data.message+"aaaa");
            }
        })
        .error(function (msg) {
            if (error != null) {
                error(msg);
            }
            else {
                error("오류가 발생하였습니다.");
            }
        });

    }
</script>

<div class="contents course_manage">
    @using (Html.BeginForm("SetUserInformation", "Common", FormMethod.Post, new { id = "userinfo", style = "margin:0 auto; margin-top: 2%" }))
    {
        @Html.HiddenFor(x => x.Item2.midx);
        @*@Html.Hidden("IsSetPasswordView", (bool)ViewBag.IsSetPasswordView)*@
    <div class="common_form">
        <table class="form_tbl">
            <colgroup>
                <col style="width: 20%;" />
                <col style="width: 80%;" />
            </colgroup>
            <tr class="top">
                <th scope="row">학교</th>
                <td>
                    @Html.DropDownListFor(x => x.Item2.sch_code, (new SelectList(Model.Item1, "sch_code", "sch_name", Model.Item2.sch_code)).ToList(), new { })
                </td>
            </tr>
            <tr>
                <th scope="row">학번</th>
                <td>
                    @{
                        var gradelist = new List<string>(new string[] { "1학년", "2학년", "3학년" });
                        var classlist = new List<string>();
                        var nolist = new List<string>();
                        for (int i = 1; i < 51; i++)
                        {
                            if (i < 16)
                            {
                                classlist.Add(string.Format("{0}반", i));
                            }
                            nolist.Add(string.Format("{0}번", i));
                        }
                    }

                    @Html.DropDownListFor(x => x.Item2.grade, new SelectList(gradelist.Select((x, idx) => new { Value = idx + 1, Text = x }), "Value", "Text", Model.Item2.grade), new { @class = "select wd1", @style = "width:120px;" })
                    @Html.DropDownListFor(x => x.Item2.mclass, new SelectList(classlist.Select((x, idx) => new { Value = idx + 1, Text = x }), "Value", "Text", Model.Item2.mclass), new { @class = "select wd1", @style = "width:120px;" })
                    @Html.DropDownListFor(x => x.Item2.no, new SelectList(nolist.Select((x, idx) => new { Value = idx + 1, Text = x }), "Value", "Text", Model.Item2.no), new { @class = "select wd1", @style = "width:120px;" })
                </td>
            </tr>
            <tr>
                <th scope="row">이름</th>
                <td>@Html.TextBoxFor(x => x.Item2.uname, new { @id = "username", @style = "ime-mode:active;" })</td>
            </tr>
            <tr>
                <th scope="row">연락처</th>
                <td>
                    <div class="telBox" style="max-width:450px;">
                        @{
                            var telcomlist = new List<string>(new string[] { "010", "011", "016", "017", "019" });
                        }
                        @Html.DropDownListFor(x => x.Item2.telcom, new SelectList(telcomlist.Select(x => new { Value = x, Text = x }), "Value", "Text", Model.Item2.telcom), new { @class = "select wd1", @style = "width:120px;" })
                        @Html.TextBoxFor(x => x.Item2.phone1, new { @class = "text wd1", @style = "width:120px;height:36px;font-family:'Arial';" }) ~ @Html.TextBoxFor(x => x.Item2.phone2, new { @class = "text wd1", @style = "width:120px;height:36px;font-family:'Arial';" })
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">성별</th>
                <td>
                    @{
                        var genderlist = new List<string>(new string[] { "남자", "여자" });
                    }
                    @Html.DropDownListFor(x => x.Item2.Gender, new SelectList(genderlist.Select((x, idx) => new { Value = idx + 1, Text = x }), "Value", "Text", Model.Item2.Gender), new { @class = "select wd1", @style = "width:120px;" })
                </td>
            </tr>
            <tr>
                <th scope="row">개인정보수집</th>
                <td>
                    <input type="checkbox" class="control-label" id="agreeinfo" /><label for="agreeinfo">개인정보 수집에 동의 합니다.</label>
                </td>
            </tr>
        </table>
        <!-- 버튼 -->
        <div class="btn_a right">
            <button type="submit" class="btn blue last" onclick="return modify();">수정</button>
            <a class="btn white" onclick="history.back()">취소</a>

        </div>
    </div>
    }
</div>